[profile.default]
src = "src"
out = "out"
libs = ["lib"]

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options

remappings = [
    '@v4-core/=lib/v4-core/contracts/',
    '@openzeppelin/=lib/openzeppelin-contracts/contracts/',
    '@chainlink/=lib/chainlink-brownie-contracts/contracts/',
    'forge-std/=lib/forge-std/src/'
]