[profile.default]
src = 'src'
out = 'out'
libs = ['lib']
solc = "0.8.19"
optimizer = true
optimizer_runs = 200

remappings = [
    '@openzeppelin/=lib/openzeppelin-contracts/',
    '@v4-core/=lib/v4-core/',
    'forge-std/=lib/forge-std/src/',
    '@chainlink/=lib/chainlink/contracts/'
]

[profile.ci]
fuzz_runs = 1000
verbosity = 4

[rpc_endpoints]
sepolia = "${SEPOLIA_RPC_URL}"
mainnet = "${MAINNET_RPC_URL}"

[etherscan]
sepolia = { key = "${ETHERSCAN_API_KEY}" }
mainnet = { key = "${ETHERSCAN_API_KEY}" }