[profile.default]
src = "contracts/src"
out = "out"
libs = ["lib"]
solc = "0.8.23"
optimizer = true
optimizer_runs = 200

remappings = [
    "@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts/",
    "forge-std/=lib/forge-std/src/",
    "@chainlink/=lib/chainlink/contracts/",
    "@uniswap/v4-core/=lib/v4-core/"
     "@openzeppelin/=lib/openzeppelin-contracts/",
    "@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts/"
    
]

[profile.ci]
fuzz_runs = 1000
verbosity = 4

[rpc_endpoints]
holesky = "${HOLESKY_RPC_URL}"

[etherscan]
holesky = { key = "${ETHERSCAN_API_KEY}" }